// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkMXHNR4Uf2AwQxDxYpXUaFYdux86fFj0',
    appId: '1:670380423303:web:8dd1ff73932e0ff3872022',
    messagingSenderId: '670380423303',
    projectId: 'cics-extensionoffice-caabb',
    authDomain: 'cics-extensionoffice-caabb.firebaseapp.com',
    storageBucket: 'cics-extensionoffice-caabb.firebasestorage.app',
    measurementId: 'G-VYHQMHTV9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADk4a5URfdxi3bbj4EnGk6Ya0rPiiaUXY',
    appId: '1:670380423303:android:c0610e31e8949460872022',
    messagingSenderId: '670380423303',
    projectId: 'cics-extensionoffice-caabb',
    storageBucket: 'cics-extensionoffice-caabb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAsZYO5YyK6EE0kQ26j-cf2FSu411qOBo',
    appId: '1:670380423303:ios:d09ba21a28c71e2f872022',
    messagingSenderId: '670380423303',
    projectId: 'cics-extensionoffice-caabb',
    storageBucket: 'cics-extensionoffice-caabb.firebasestorage.app',
    iosBundleId: 'com.example.cicsextensionOffiice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAsZYO5YyK6EE0kQ26j-cf2FSu411qOBo',
    appId: '1:670380423303:ios:d09ba21a28c71e2f872022',
    messagingSenderId: '670380423303',
    projectId: 'cics-extensionoffice-caabb',
    storageBucket: 'cics-extensionoffice-caabb.firebasestorage.app',
    iosBundleId: 'com.example.cicsextensionOffiice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkMXHNR4Uf2AwQxDxYpXUaFYdux86fFj0',
    appId: '1:670380423303:web:59730b08a7adda36872022',
    messagingSenderId: '670380423303',
    projectId: 'cics-extensionoffice-caabb',
    authDomain: 'cics-extensionoffice-caabb.firebaseapp.com',
    storageBucket: 'cics-extensionoffice-caabb.firebasestorage.app',
    measurementId: 'G-Z5WV9YC1E1',
  );
}
